// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_flying_high = "CgkI9a6HncYcEAIQAw"; // <GPGSID>
        public const string achievement_catgroove = "CgkI9a6HncYcEAIQCA"; // <GPGSID>
        public const string achievement_gold_digger = "CgkI9a6HncYcEAIQBw"; // <GPGSID>
        public const string achievement_blackjack = "CgkI9a6HncYcEAIQCQ"; // <GPGSID>
        public const string achievement_cant_touch_me = "CgkI9a6HncYcEAIQBg"; // <GPGSID>
        public const string achievement_dog_person = "CgkI9a6HncYcEAIQBA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI9a6HncYcEAIQAQ"; // <GPGSID>
        public const string achievement_dog_master = "CgkI9a6HncYcEAIQCw"; // <GPGSID>
        public const string achievement_sky_is_the_limit = "CgkI9a6HncYcEAIQBQ"; // <GPGSID>
        public const string achievement_first_100 = "CgkI9a6HncYcEAIQAg"; // <GPGSID>
        public const string achievement_electric_guillotine = "CgkI9a6HncYcEAIQDA"; // <GPGSID>
        public const string achievement_catastic = "CgkI9a6HncYcEAIQCg"; // <GPGSID>

}

